# Permalinks
#
permalink:           pretty

# Setup
title:               Nir's blog
tagline:             'Fit for computer consumption'
description:         'Code, math, and all that good stuff.'
url:                 http://quicknir.github.io
baseurl:             ''
gems: [jekyll-paginate hawkins]
paginate:            5
future: true

# About/contact
author:
  name:              Nir Friedman
  email:             quicknir@gmail.com

# Custom vars
version:             1.0.0
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      disqusid: "1"
      comments: true

# Disqus
disqus: "turingtested"
